"""empty message

Revision ID: 19e88fecada7
Revises: 
Create Date: 2025-04-03 00:44:47.116193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19e88fecada7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Air_Control_Dep',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Flights',
    sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('departure_airport', sa.String(length=10), nullable=False),
    sa.Column('arrival_airport', sa.String(length=10), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('account_status', sa.SmallInteger(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Admin_Activity_Log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['Admin.admin_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('Air_Control_Activity_Log',
    sa.Column('ac_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['Flights.flight_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['Air_Control_Dep.staff_id'], ),
    sa.PrimaryKeyConstraint('ac_log_id')
    )
    op.create_table('Bookings',
    sa.Column('bookings_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('extra_baggage', sa.SmallInteger(), nullable=False),
    sa.Column('travel_insurance', sa.SmallInteger(), nullable=False),
    sa.Column('booking_status', sa.String(length=50), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['Flights.flight_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('bookings_id')
    )
    op.create_table('Feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['Flights.flight_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('Payment_Methods',
    sa.Column('payment_method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_token', sa.String(length=255), nullable=False),
    sa.Column('card_last_four', sa.CHAR(length=4), nullable=False),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('expiration_month', sa.SmallInteger(), nullable=True),
    sa.Column('expiration_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_default', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('payment_method_id')
    )
    op.create_table('Transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_status', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['Payment_Methods.payment_method_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('flights')
    op.drop_table('feedback')
    with op.batch_alter_table('air_control_dep', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('air_control_dep')
    op.drop_table('payment_methods')
    op.drop_table('bookings')
    op.drop_table('air_control_activity_log')
    op.drop_table('admin_activity_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    op.drop_table('transaction')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('admin')
    with op.batch_alter_table('manages', schema=None) as batch_op:
        batch_op.drop_constraint('manages_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('manages_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Air_Control_Dep', ['staff_id'], ['staff_id'])
        batch_op.create_foreign_key(None, 'Flights', ['flight_id'], ['flight_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manages_ibfk_2', 'flights', ['flight_id'], ['flight_id'])
        batch_op.create_foreign_key('manages_ibfk_1', 'air_control_dep', ['staff_id'], ['staff_id'])

    op.create_table('admin',
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=511), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('transaction',
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transaction_status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('payment_method_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], name='transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('transaction_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=511), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('account_status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'user'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('admin_activity_log',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('activity_timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], name='admin_activity_log_ibfk_1'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('air_control_activity_log',
    sa.Column('ac_log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('activity_timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], name='air_control_activity_log_ibfk_1'),
    sa.ForeignKeyConstraint(['staff_id'], ['air_control_dep.staff_id'], name='air_control_activity_log_ibfk_2'),
    sa.PrimaryKeyConstraint('ac_log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookings',
    sa.Column('bookings_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seat_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('extra_baggage', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('travel_insurance', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('booking_status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('booking_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('total_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], name='bookings_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='bookings_ibfk_1'),
    sa.PrimaryKeyConstraint('bookings_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment_methods',
    sa.Column('payment_method_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('payment_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('card_last_four', mysql.CHAR(length=4), nullable=False),
    sa.Column('card_brand', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('expiration_month', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('expiration_year', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_default', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='payment_methods_ibfk_1'),
    sa.PrimaryKeyConstraint('payment_method_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('air_control_dep',
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'air control staff'"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=511), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('air_control_dep', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.create_table('feedback',
    sa.Column('feedback_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('feedback_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], name='feedback_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='feedback_ibfk_1'),
    sa.PrimaryKeyConstraint('feedback_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('flights',
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('airline', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('departure_airport', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('arrival_airport', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('total_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('flight_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Transaction')
    op.drop_table('Payment_Methods')
    op.drop_table('Feedback')
    op.drop_table('Bookings')
    op.drop_table('Air_Control_Activity_Log')
    op.drop_table('Admin_Activity_Log')
    op.drop_table('User')
    op.drop_table('Flights')
    op.drop_table('Air_Control_Dep')
    op.drop_table('Admin')
    # ### end Alembic commands ###
